<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LIN-2K3R9K3" failures="1" tests="5" name="Listener Test Case" time="0.009" errors="0" timestamp="2024-10-14T13:20:22 IST">
  <testcase classname="com.testng.listeners.SampleTestCase" name="testFour" time="0.001">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="com.testng.listeners.SampleTestCase" name="testGetData" time="0.001"/>
  <testcase classname="com.testng.listeners.SampleTestCase" name="testGetData" time="0.001"/>
  <testcase classname="com.testng.listeners.SampleTestCase" name="testOne" time="0.0"/>
  <testcase classname="com.testng.listeners.SampleTestCase" name="testThree" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at com.testng.listeners.SampleTestCase.testThree(SampleTestCase.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- Listener Test Case -->
